template:
  languages: &LANGUAGES
    - Scala
  issue: &CODE_DUPLICATION_ISSUE
    category: Code Duplication
    type: Duplicated Code
    severity: Warning
    weight: 1

default:
  context:
    languages: *LANGUAGES
  report:
